### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by jayceazua** [ar-hunt/docs#1]

**Comment by Xisouyang** [comment]
![iphone 6-7-8 1](https://user-images.githubusercontent.com/42627387/51875002-06b19780-2318-11e9-915e-532a8d628bf2.jpg)
![iphone 6-7-8 2](https://user-images.githubusercontent.com/42627387/51875003-074a2e00-2318-11e9-8d24-33dee1a95899.jpg)
![iphone 6-7-8 3](https://user-images.githubusercontent.com/42627387/51875004-074a2e00-2318-11e9-8a74-4d71b3aa2648.jpg)
![iphone 6-7-8 4](https://user-images.githubusercontent.com/42627387/51875005-074a2e00-2318-11e9-93ef-26d528ec4504.jpg)
![iphone 6-7-8 5](https://user-images.githubusercontent.com/42627387/51875006-074a2e00-2318-11e9-94d6-1a5a6548c10b.jpg)
![iphone 6-7-8 6](https://user-images.githubusercontent.com/42627387/51875007-074a2e00-2318-11e9-94b1-6b52be508c98.jpg)
![iphone 6-7-8 7](https://user-images.githubusercontent.com/42627387/51875008-074a2e00-2318-11e9-9bea-7d754c87a069.jpg)

**Comment by Xisouyang** [comment]
<img width="870" alt="screen shot 2019-02-06 at 11 20 16 am" src="https://user-images.githubusercontent.com/42627387/52367641-62a7aa80-2a01-11e9-9d03-56f7d882e69b.png">
