### ISSUE TITLE
Define Ready, Done, Shipped

### ISSUE THREAD

**Issue by jayceazua** [ar-hunt/docs#10]
Each member of the team will define ready, done, shipped and what it means to the team

**Comment by ryanlsmith4** [comment]
Got it done on our AR hunt docs page

**Comment by ryanlsmith4** [comment]
Got it done on the AR docs page here https://docs.google.com/document/d/1klXVIqhAaAk6NC_TquH3MntzHB-KAr-W_Xg16FK_1ZI/edit#
